SET CONDA_PATH=%EWS_PROGRAMS_PATH%\miniconda2
call "%CONDA_PATH%\Scripts\activate"
SET CONDARC=%CONDA_PREFIX%\.condarc
SET CONDA_ENVS_PATH=%CONDA_PREFIX%\envs
SET CONDA_PKGS_DIRS=%CONDA_PREFIX%\pkgs
SET "MKL_THREADING_LAYER=GNU"
